name: Deploy
on:
  push:
    branches: ["v2"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        run: sudo apt-get install hugo -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
